const ALLOWED_ORIGINS=['https://tillie007.github.io','https://receptenboek-gold.vercel.app','https://receptenboek-timvan-camp-9476.vercel.app'];
function cors(req,res){const o=req.headers.origin||'';if(ALLOWED_ORIGINS.includes(o))res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Vary','Origin')}
function isPrivateHost(host){const h=host.toLowerCase();return h==='localhost'||h==='127.0.0.1'||h==='0.0.0.0'||h==='::1'||h.endsWith('.local')||/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h)||/^172\.(1[6-9]|2\d|3[01])\./.test(h)}
function decodeEntities(s=''){return String(s).replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&eacute;/gi,'é').replace(/&egrave;/gi,'è').replace(/&agrave;/gi,'à').replace(/&uuml;/gi,'ü').replace(/&ouml;/gi,'ö').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n))}
function stripHtml(s=''){return decodeEntities(String(s).replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]*>/g,' ')).replace(/[ \t]+/g,' ').replace(/\s*\n\s*/g,'\n').trim()}
function findRecipes(o,out=[]){if(!o)return out;if(Array.isArray(o)){for(const x of o)findRecipes(x,out)}else if(typeof o==='object'){const t=o['@type'];if(t==='Recipe'||(Array.isArray(t)&&t.includes('Recipe')))out.push(o);for(const [k,v] of Object.entries(o)){if(k!=='@context'&&k!=='@type')findRecipes(v,out)}}return out}
function typeOf(x){const t=x?.['@type'];return Array.isArray(t)?t:[t].filter(Boolean)}
function instructions(v){if(!v)return[];if(typeof v==='string')return v.split(/\n+/).map(stripHtml).filter(Boolean);if(Array.isArray(v))return v.flatMap(instructions).filter(Boolean);if(typeof v!=='object')return[];const types=typeOf(v),nested=v.itemListElement||v.steps||v.recipeInstructions||v.itemList;if(types.includes('HowToSection')||nested){const name=stripHtml(v.name||v.headline||''),children=instructions(nested);return name&&children.length?[`§ ${name}`,...children]:children}const text=stripHtml(v.text||v.description||v.name||'');return text?[text]:[]}
function author(v){if(!v)return'';if(typeof v==='string')return v;if(Array.isArray(v))return v.map(author).filter(Boolean).join(', ');return v.name||''}
function image(v){if(!v)return'';if(typeof v==='string')return v;if(Array.isArray(v))return image(v[0]);return v.url||v.contentUrl||''}
function decodeJsonLd(raw){for(const c of [raw,raw.replace(/[\u0000-\u001F]+/g,' ')]){try{return JSON.parse(c)}catch{}}return null}
function parseJsonLd(html){const re=/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m,best=null,bestScore=-1;while((m=re.exec(html))){const obj=decodeJsonLd(m[1].trim());for(const r of findRecipes(obj,[])){const score=(Array.isArray(r.recipeIngredient)?r.recipeIngredient.length:0)+instructions(r.recipeInstructions).filter(x=>!x.startsWith('§ ')).length*3;if(score>bestScore){best=r;bestScore=score}}}return best}
function cleanStep(s=''){s=stripHtml(s).replace(/^\s*(?:stap\s*)?\d+[.)\-:]?\s*/i,'').trim();return s.length>2?s:''}
function norm(s=''){return stripHtml(s).toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim()}
function dedupeStructured(items){const out=[],seen=new Set();for(const raw of items||[]){if(!raw)continue;if(raw.startsWith('§ ')){const title=stripHtml(raw.slice(2));if(!title)continue;const key='h:'+norm(title);if(out.length&&out[out.length-1].startsWith('§ ')&&norm(out[out.length-1].slice(2))===norm(title))continue;if(seen.has(key)&&out.some(x=>x.startsWith('§ ')&&norm(x.slice(2))===norm(title)))continue;out.push('§ '+title);seen.add(key);continue}const step=cleanStep(raw),key='s:'+norm(step);if(!step||seen.has(key))continue;seen.add(key);out.push(step)}while(out.length&&out[out.length-1].startsWith('§ '))out.pop();return out}
function jsonSections(r){const raw=instructions(r?.recipeInstructions);return dedupeStructured(raw)}
function htmlPreparation(html){
  let zone=html;
  const starts=[...html.matchAll(/>\s*(?:Bereiding|Bereidingswijze|Voorbereiding)\s*</gi)].map(m=>m.index).filter(Number.isFinite);
  if(starts.length)zone=html.slice(Math.min(...starts),Math.min(html.length,Math.min(...starts)+300000));
  const stop=zone.search(/>\s*(?:Tips?|Notities?|Reacties?|Meer recepten)\s*</i);if(stop>500)zone=zone.slice(0,stop);
  const out=[];let currentSection='';
  const token=/<(h[2-6]|li|p)\b([^>]*)>([\s\S]*?)<\/\1>/gi;let m;
  const heading=t=>{t=stripHtml(t);if(!t||t.length>90)return'';if(/^(ingrediënten|ingredienten|recept|tips?|notities?)$/i.test(t))return'';return t};
  const pushHeading=t=>{t=heading(t);if(!t)return;if(/^bereiding(?:swijze)?$/i.test(t)&&out.length===0){currentSection='Bereiding';return}currentSection=t;if(out.length&&out[out.length-1]===`§ ${t}`)return;out.push(`§ ${t}`)};
  while((m=token.exec(zone))&&out.length<160){
    const tag=m[1].toLowerCase(),attrs=m[2]||'',raw=m[3]||'',text=stripHtml(raw);if(!text)continue;
    if(tag[0]==='h'){pushHeading(text);continue}
    const classStep=/(step|instruction|preparation|method|recipe)/i.test(attrs),numbered=/^\s*(?:stap\s*)?\d+[.)\-:]?\s*/i.test(text);
    if(!classStep&&!numbered)continue;
    const step=cleanStep(text);if(!step||step.length<8)continue;
    if(currentSection&&(!out.length||(!out[out.length-1].startsWith('§ ')&&!out.some((x,i)=>x===`§ ${currentSection}`&&i>out.length-12))))out.push(`§ ${currentSection}`);
    out.push(step)
  }
  return dedupeStructured(out)
}
function mergeBestSections(json,html){const j=dedupeStructured(json),h=dedupeStructured(html),jSteps=j.filter(x=>!x.startsWith('§ ')),hSteps=h.filter(x=>!x.startsWith('§ ')),jHeads=j.filter(x=>x.startsWith('§ ')),hHeads=h.filter(x=>x.startsWith('§ '));if(hSteps.length>=3&&hHeads.length>=2)return h;if(jSteps.length>=3&&jHeads.length)return j;if(hSteps.length>jSteps.length)return h;return j}
function normalize(r,url,html){const cat=Array.isArray(r.recipeCategory)?r.recipeCategory.join(', '):(r.recipeCategory||''),y=Array.isArray(r.recipeYield)?r.recipeYield.join(', '):(r.recipeYield||'');const steps=mergeBestSections(jsonSections(r),htmlPreparation(html));return{title:stripHtml(r.name||''),type:stripHtml(cat),season:'',servings:stripHtml(y),wine:'',chef:stripHtml(author(r.author)),rating:0,source:url,image:image(r.image),ingredients:(r.recipeIngredient||[]).map(stripHtml).filter(Boolean),steps,notes:'',prepTime:r.prepTime||'',cookTime:r.cookTime||'',totalTime:r.totalTime||'',cuisine:Array.isArray(r.recipeCuisine)?r.recipeCuisine.join(', '):(r.recipeCuisine||'')}}
export default async function handler(req,res){cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({error:'Gebruik POST.'});try{const input=typeof req.body==='string'?JSON.parse(req.body):req.body,target=new URL(input?.url||'');if(!['http:','https:'].includes(target.protocol)||isPrivateHost(target.hostname))return res.status(400).json({error:'Ongeldige receptlink.'});const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);const upstream=await fetch(target.toString(),{signal:controller.signal,redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; MijnRecepten/1.4)','Accept':'text/html,application/xhtml+xml'}});clearTimeout(timer);if(!upstream.ok)throw new Error('Website antwoordde met '+upstream.status);if(!(upstream.headers.get('content-type')||'').includes('text/html'))throw new Error('De link is geen webpagina.');const html=(await upstream.text()).slice(0,5000000),recipe=parseJsonLd(html);if(!recipe)return res.status(422).json({error:'Geen gestructureerd recept gevonden op deze pagina.'});return res.status(200).json({ok:true,recipe:normalize(recipe,target.toString(),html)})}catch(e){return res.status(400).json({error:e?.name==='AbortError'?'De website reageerde te traag.':(e?.message||'Importeren mislukt.')})}}
